apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: auth
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: aravindor/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
manifests:
  rawYaml:
    - ./infra/k8s/*
